version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rL1XSezBGxye7A4m
      - log_destination=stderr
      - logging_collector=on
      - log_directory=/var/lib/postgresql/logs/
    ports:
      - "5432:5432"
    volumes:
      - ./project/database/db/:/var/lib/postgresql/data